apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis:5.0.4
    command: ["bash", "-c", "redis-server /redis-master/redis.conf"]
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    volumeMounts:
    - mountPath: /redis-master
      name: config
  volumes:
    - name: config
      configMap:
        name: qiusuo-redis-config
        items:
        - key: redis-config
          path: redis.conf
---
kind: Service
apiVersion: v1
metadata:
  name: redis
spec:
  ports:
    - name: 6379-6379
      port: 6379
      protocol: TCP
      targetPort: 6379
  type: ClusterIP
  selector:
    app: redis


