apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-mysql
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: mysql-pv