apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: test-mysql
spec:
  containers:
    - image: mysql:5.7
      name: test-mysql
      imagePullPolicy: IfNotPresent
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: qiusuo
        - name: MYSQL_DATABASE
          value: qiusuo
        - name: MYSQL_USER
          value: qiusuo
        - name: MYSQL_PASSWORD
          value: qiusuo
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  ports:
    - name: 4406-3306
      port: 4406
      protocol: TCP
      targetPort: 3306
  type: ClusterIP
  selector:
    app: test-mysql
