apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  clusterIP: None
  ports:
    - port: 7000
      name: 7000-7000
    - port: 7001
      name: 7001-7001
    - port: 7199
      name: 7199-7199
    - port: 9042
      name: 9042-9042
  selector:
    app: cassandra
