apiVersion: v1
kind: Pod
metadata:
  name: cassandra-pod
  labels:
    app: test-cassandra
spec:
    containers:
    - image: cassandra:latest
      name: test-cassandra
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 7000
      - containerPort: 9042
      volumeMounts:
        - name: cassandra-pvc-data
          mountPath: /var/lib/cassandra
        - name: cassandra-pvc-conf
          mountPath: /etc/cassandra
    volumes:
      - name: cassandra-pvc-data
        persistentVolumeClaim:
          claimName: cassandra-pvc-data
      - name: cassandra-pvc-conf
        persistentVolumeClaim:
          claimName: cassandra-pvc-conf
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-svc
spec:
  ports:
    - name: 7000-7000
      port: 7000
      protocol: TCP
      targetPort: 7000
    - name: 9042-9042
      port: 9042
      protocol: TCP
      targetPort: 9042
  type: ClusterIP
  selector:
    app: test-cassandra
